// <auto-generated />
using System;
using Meal_Planner_Page.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Meal_Planner_Page.Migrations
{
    [DbContext(typeof(MealContext))]
    [Migration("20250326172610_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MealItem", b =>
                {
                    b.Property<int>("MealId")
                        .HasColumnType("int")
                        .HasColumnName("meal_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.HasKey("MealId", "ItemId")
                        .HasName("meal_items_pk");

                    b.HasIndex("ItemId");

                    b.ToTable("meal_items", (string)null);
                });

            modelBuilder.Entity("Meal_Planner_Page.Models.FoodItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<float?>("ServingSize")
                        .HasColumnType("real")
                        .HasColumnName("serving_size");

                    b.HasKey("ItemId")
                        .HasName("food_Items_pk");

                    b.ToTable("food_Items", (string)null);
                });

            modelBuilder.Entity("Meal_Planner_Page.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ingredient_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<float>("Calories")
                        .HasColumnType("real")
                        .HasColumnName("calories");

                    b.Property<float>("DietaryFiber")
                        .HasColumnType("real")
                        .HasColumnName("dietary_fiber");

                    b.Property<int>("MId")
                        .HasColumnType("int")
                        .HasColumnName("m_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<float>("Protein")
                        .HasColumnType("real")
                        .HasColumnName("protein");

                    b.Property<float>("Sodium")
                        .HasColumnType("real")
                        .HasColumnName("sodium");

                    b.Property<float>("TotalFat")
                        .HasColumnType("real")
                        .HasColumnName("total_fat");

                    b.Property<float>("TotalSugers")
                        .HasColumnType("real")
                        .HasColumnName("total_sugers");

                    b.HasKey("IngredientId")
                        .HasName("ingredients_pk");

                    b.HasIndex("MId");

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("Meal_Planner_Page.Models.Meal", b =>
                {
                    b.Property<int>("MealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("meal_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MealId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("MealId")
                        .HasName("meals_pk");

                    b.ToTable("meals", (string)null);
                });

            modelBuilder.Entity("Meal_Planner_Page.Models.Measurement", b =>
                {
                    b.Property<int>("MId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("m_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("MId")
                        .HasName("measurement_pk");

                    b.ToTable("measurement", (string)null);
                });

            modelBuilder.Entity("Meal_Planner_Page.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int")
                        .HasColumnName("ingredient_id");

                    b.Property<float>("Amount")
                        .HasColumnType("real")
                        .HasColumnName("amount");

                    b.HasKey("ItemId", "IngredientId")
                        .HasName("recipe_ingredients_pk");

                    b.HasIndex("IngredientId");

                    b.ToTable("recipe_ingredients", (string)null);
                });

            modelBuilder.Entity("MealItem", b =>
                {
                    b.HasOne("Meal_Planner_Page.Models.FoodItem", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("meal_items_food_Items");

                    b.HasOne("Meal_Planner_Page.Models.Meal", null)
                        .WithMany()
                        .HasForeignKey("MealId")
                        .IsRequired()
                        .HasConstraintName("meal_items_meals");
                });

            modelBuilder.Entity("Meal_Planner_Page.Models.Ingredient", b =>
                {
                    b.HasOne("Meal_Planner_Page.Models.Measurement", "MIdNavigation")
                        .WithMany("Ingredients")
                        .HasForeignKey("MId")
                        .IsRequired()
                        .HasConstraintName("ingredients_measurement");

                    b.Navigation("MIdNavigation");
                });

            modelBuilder.Entity("Meal_Planner_Page.Models.RecipeIngredient", b =>
                {
                    b.HasOne("Meal_Planner_Page.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .IsRequired()
                        .HasConstraintName("recipe_ingredients_ingredients");

                    b.HasOne("Meal_Planner_Page.Models.FoodItem", "Item")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("recipe_ingredients_food_Items");

                    b.Navigation("Ingredient");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Meal_Planner_Page.Models.FoodItem", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("Meal_Planner_Page.Models.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("Meal_Planner_Page.Models.Measurement", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
